const products=[{id:1,name:'The Aurelia',price_cents:89500,meta:'Patent Leather | Crystal Embellishment'},{id:2,name:'The Vérilyn',price_cents:129000,meta:'Satin | Handcrafted Bow'},{id:3,name:'The Isadora',price_cents:79500,meta:'Metallic Leather | Sculpted Heel'},{id:4,name:'The Celeste',price_cents:115000,meta:'Suede | Gold Detail'},{id:5,name:'The Seraphine',price_cents:149000,meta:'Embroidered Mesh | Pearl Detail'}];
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(c/100);
let bag=JSON.parse(localStorage.getItem('classyheels-bag')||'[]');
const grid=document.querySelector('#productGrid');
products.forEach((p,i)=>grid.insertAdjacentHTML('beforeend',`<article class="product"><button class="heart">♡</button><div class="productImg product-${i+1}"></div><h3>${p.name}</h3><div class="price">${money(p.price_cents)}</div><div class="meta">${p.meta}</div><button class="add" data-i="${i}">Add to bag</button></article>`));
function save(){localStorage.setItem('classyheels-bag',JSON.stringify(bag));}
function render(){document.querySelector('#cartCount').textContent=bag.reduce((n,x)=>n+x.quantity,0);document.querySelector('#cartItems').innerHTML=bag.length?bag.map((p,i)=>`<div class="cartRow"><div><b>${p.name}</b><small>${money(p.price_cents)} · Qty ${p.quantity}</small></div><button onclick="bag.splice(${i},1);save();render()">Remove</button></div>`).join(''):'Your bag is empty.';const btn=document.querySelector('.checkout');btn.disabled=!bag.length;btn.textContent=bag.length?'Checkout securely →':'Your bag is empty';}
function openCart(){document.querySelector('#cart').classList.add('open');document.querySelector('#overlay').classList.add('show')}
document.addEventListener('click',e=>{if(e.target.matches('.add')){const p=products[+e.target.dataset.i], existing=bag.find(x=>x.id===p.id);existing?existing.quantity++:bag.push({...p,quantity:1});save();render();openCart()}});
document.querySelector('#cartBtn').onclick=openCart;function closeCart(){document.querySelector('#cart').classList.remove('open');document.querySelector('#overlay').classList.remove('show')}document.querySelector('#close').onclick=closeCart;document.querySelector('#overlay').onclick=closeCart;document.querySelector('#menu').onclick=()=>document.querySelector('#mobileNav').classList.toggle('open');document.querySelector('.checkout').onclick=()=>{if(bag.length)location.href='/checkout.html'};render();
